ALTER PROC INSERTARPRODUCTO @IDPRO INT,@COD VARCHAR(20),@NOM VARCHAR(60), @MAR VARCHAR(80),@CON VARCHAR(20),@CAT VARCHAR(25),@PRECO FLOAT,@PREVE FLOAT,@DES VARCHAR(100),@UBI VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM PRODUCTO WHERE IDPRODUCTO = @IDPRO)
		BEGIN
		UPDATE PRODUCTO SET Codigo=@COD,Nombre=@NOM,Categoria=@CAT,PrecioCompra=@PRECO,PrecioVenta=@PREVE,Descripcion=@DES,MARCA=@MAR,CONTENIDO=@CON
		WHERE IdProducto=@IDPRO
		UPDATE ALMACEN SET UBICACION=@UBI WHERE IdProducto=@IDPRO
		END
	ELSE
		BEGIN
		INSERT INTO PRODUCTO VALUES(@COD,@NOM,@CAT,'',@PRECO,@PREVE,@DES,'1',@MAR,@CON)
		SET @IDPRO = (SELECT IDPRODUCTO FROM PRODUCTO WHERE CODIGO=@COD)
		INSERT INTO ALMACEN VALUES(@IDPRO,0,@UBI)
		IF @COD=''
			UPDATE PRODUCTO SET CODIGO=@IDPRO WHERE IDPRODUCTO=@IDPRO
		END


EXEC INSERTARPRODUCTO -1,'7771224002387','HELADO','DELIZIA BROWNIE','100 ML.','HELADOS',0,6,'','LADO IZQUIERDO'
EXEC INSERTARPRODUCTO -1,'','ESTILETE','CUTTER KNIFE','1 UN.','HUEVOS Y LACTEOS',0,2,'','LADO ENTRADA'



CREATE PROC ELIMINARPRODUCTO @IDPRO INT
AS
	UPDATE PRODUCTO SET ESTADO='0' WHERE IDPRODUCTO=@IDPRO

	
ALTER PROC INSERTARALMACEN @IDPRO INT,@CAN INT
AS
	UPDATE ALMACEN SET Cantidad = Cantidad + @CAN WHERE IdProducto = @IDPRO
	EXEC INSERTARLOTE 24,8,'19/02/2020',100,3,15

ALTER PROC INSERTARLOTE @IDPRO INT,@IDCO INT,@EXP VARCHAR(12),@COS FLOAT,@CANPA INT,@CANEN INT,@PRECO FLOAT
AS
	DECLARE @CAN INT
	SET @CAN = @CANPA * @CANEN
	INSERT INTO LOTE VALUES(@IDPRO,@IDCO,@EXP,@CAN,@PRECO,@COS,@CANPA,@CANEN)
	EXEC INSERTARALMACEN @IDPRO,@CAN
	UPDATE PRODUCTO SET PRECIOCOMPRA=@PRECO WHERE IDPRODUCTO=@IDPRO
	
CREATE PROC GETULTIMACOMPRA
AS
	SELECT IDCOMPRA FROM COMPRA WHERE ULTIMO='1'
	
CREATE PROC GETULTIMAVENTA
AS
	SELECT IDVENTA FROM VENTA WHERE ULTIMO='1'

	select * from DISTRIBUIDORA

			EXEC INSERTARCOMPRA 160,'MI PRIMER COMPRA','PIL','','',''
			select * from lote
			select * from compra
			insert into lote values(36,1015,getdate(),3,3.33,10,1,3)

ALTER PROC INSERTARCOMPRA @COS FLOAT,@DES VARCHAR(200),@DIS VARCHAR(60),@DIR VARCHAR(60),@TEL VARCHAR(20),@CAT VARCHAR(25),@USU INT
AS
	DECLARE @ID INT
	IF NOT EXISTS(SELECT * FROM DISTRIBUIDORA WHERE NOMBRE=@DIS)
		INSERT INTO DISTRIBUIDORA VALUES(@DIS,@DIR,@TEL,@CAT)
	SET @ID = (SELECT IDDISTRIBUIDORA FROM DISTRIBUIDORA WHERE NOMBRE=@DIS)
	INSERT INTO COMPRA VALUES(GETDATE(),@COS,1,@DES,@ID,@USU)

	SELECT * FROM DISTRIBUIDORA

ALTER PROC EDITARCOMPRA @IDCOM INT,@COS FLOAT,@DES VARCHAR(100)
AS
	UPDATE COMPRA SET CostoTotal=@COS,ULTIMO='1',DESCRIPCION=@DES WHERE IdCompra=@IDCOM

CREATE PROC CERRARCOMPRA @IDCOM INT
AS
	UPDATE COMPRA SET ULTIMO = '0' WHERE IDCOMPRA = @IDCOM

CREATE PROC ELIMINARCONTROL @IDLO INT
AS
	DELETE FROM CONTROLP WHERE IDLOTE=@IDLO
	select * from compra
CREATE PROC ELIMINARCOMPRA @IDCOM INT
AS
	DELETE FROM COMPRA WHERE IdCompra=@IDCOM

ALTER PROC INSERTARUSUARIO @ID INT,@CI VARCHAR(20),@NOM VARCHAR(60),@APE VARCHAR(60),@TEL VARCHAR(20),@EM VARCHAR(40),@DIR VARCHAR(60),@ROL CHAR(1),@EST CHAR(1),@CON VARCHAR(20),@SUE FLOAT
AS
	IF EXISTS(SELECT * FROM USUARIO WHERE IDUSUARIO=@ID)
		UPDATE USUARIO SET CIUsuario=@CI,Nombres=@NOM,Apellidos=@APE,Telefono=@TEL,Email=@EM,Direccion=@DIR,ROL=@ROL,ESTADO=@EST,CONTRASENA=@CON,SUELDO=@SUE WHERE IDUSUARIO=@ID
	ELSE
		INSERT INTO USUARIO VALUES(@CI,@NOM,@APE,@TEL,@EM,@DIR,@ROL,'1',@CON,@SUE)
		
CREATE PROC ELIMINARUSUARIO @ID INT
AS
	UPDATE USUARIO SET ESTADO='0' WHERE IDUSUARIO=@ID
	delete from cliente where IdCliente = 3
ALTER PROC INSERTARCLIENTE @ID INT,@CI VARCHAR(20),@NOM VARCHAR(60),@TEL VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM CLIENTE WHERE IDCLIENTE=@ID)
		UPDATE CLIENTE SET CICliente=@CI,Nombres=@NOM,Telefono=@TEL WHERE IdCliente=@ID
	ELSE
		INSERT INTO CLIENTE VALUES(@CI,@NOM,@TEL)
		
ALTER PROC ELIMINARUSUARIO @ID INT
AS
	UPDATE USUARIO SET ESTADO='0' WHERE IDUSUARIO=@ID

ALTER PROC INSERTARVENTA @IDUSU INT,@CI VARCHAR(20),@NOM VARCHAR(60),@TEL VARCHAR(20),@COS FLOAT,@EFE FLOAT,@CAM FLOAT,@PA VARCHAR(10)
AS
	DECLARE @IDCLI INT
	IF NOT EXISTS(SELECT * FROM CLIENTE WHERE CICLIENTE=@CI)
		INSERT INTO CLIENTE VALUES(@CI,@NOM,@TEL)
	SET @IDCLI = (SELECT IDCLIENTE FROM CLIENTE WHERE CICLIENTE=@CI)
	INSERT INTO VENTA VALUES(@IDUSU,@IDCLI,GETDATE(),@COS,@EFE,@CAM,'1','1',@PA,'')

CREATE PROC EDITARVENTA @IDVEN INT,@COS FLOAT,@EFE FLOAT,@CAM FLOAT
AS
	UPDATE VENTA SET CostoTotal=@COS,Efectivo=@EFE,Cambio=@CAM WHERE IdVenta=@IDVEN

ALTER PROC BAJAVENTA @IDVEN INT
AS
	UPDATE VENTA SET ESTADO='0' WHERE IDVENTA=@IDVEN

CREATE PROC CERRARVENTA @IDVEN INT
AS
	UPDATE VENTA SET ULTIMO='0' WHERE IDVENTA=@IDVEN

ALTER PROC REDUCIRCONTROL @IDPRO INT,@CAN INT
AS
	DECLARE @IDLO INT,@AUX INT
	WHILE @CAN>0
		BEGIN
			SELECT @IDLO=MIN(IDLOTE),@AUX=CANTIDAD FROM CONTROLP
			WHERE Cantidad>0 AND IDPRODUCTO=@IDPRO
			GROUP BY IDLOTE,EXPIRACION,CANTIDAD
			HAVING Expiracion = (SELECT MIN(EXPIRACION)FROM CONTROLP WHERE CANTIDAD>0 AND IDPRODUCTO=@IDPRO)
			-----AQUI PUEDE ENTRAR EL FACTOR NULL
				IF @AUX>=@CAN
					BEGIN
					UPDATE CONTROLP SET CANTIDAD = CANTIDAD - @CAN WHERE IDLOTE=@IDLO
					SET @CAN = 0
					END
				ELSE
					BEGIN
					UPDATE CONTROLP SET CANTIDAD = 0 WHERE IDLOTE=@IDLO
					SET @CAN = @CAN - @AUX
					END

		END

				SELECT * FROM LISTARPRODUCTOS


				UPDATE PRODUCTO SET NOMBRE = 'CEPILLO DENTAL',MARCA='COLGATE NORMAL' WHERE IDPRODUCTO=1042
				UPDATE PRODUCTO SET NOMBRE = 'CEPILLO DENTAL',MARCA='ASTRAL NORMAL' WHERE IDPRODUCTO=1043
				
ALTER PROC INSERTARLOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT,@PREVE FLOAT,@COS FLOAT
AS
	DECLARE @NCAN INT
	SET @NCAN = @CAN * (-1)
	INSERT INTO LOTEVENTA VALUES(@IDVEN,@IDPRO,@CAN,@PREVE,'1',@COS)
	EXEC INSERTARALMACEN @IDPRO,@NCAN
	EXEC REDUCIRCONTROL @IDPRO,@CAN

	SELECT * FROM CONTROLP CP INNER JOIN ALMACEN A ON CP.IdProducto = A.IdProducto
	SELECT * FROM COMPRA C INNER JOIN LOTE L ON C.IDCOMPRA=L.IDCOMPRA

	select * from LISTARVENTAS
	select * from venta

ALTER PROC DARBAJAVENTA @IDVEN INT,@DES VARCHAR(120)
AS
	UPDATE VENTA SET ESTADO='0',DESCRIPCION=@DES WHERE IDVENTA=@IDVEN
	UPDATE LOTEVENTA SET ESTADO='0' WHERE IDVENTA=@IDVEN
	SELECT * FROM LOTEVENTA WHERE IDVENTA=@IDVEN

ALTER PROC ELIMINARVENTA @IDVEN INT,@BAN INT
AS
	IF @BAN=1
		EXEC DARBAJAVENTA @IDVEN
	DELETE FROM VENTA WHERE IDVENTA=@IDVEN

ALTER PROC ELIMINARLOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT,@BAN INT
AS
	IF @BAN=1
		EXEC DARBAJALOTEVENTA @IDVEN,@IDPRO,@CAN
	DELETE FROM LOTEVENTA WHERE IDVENTA=@IDVEN AND IDPRODUCTO=@IDPRO

ALTER PROC DARBAJALOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT
AS
	DECLARE @IDLO INT,@AUX INT
	UPDATE ALMACEN SET CANTIDAD = CANTIDAD + @CAN WHERE IDPRODUCTO=@IDPRO
	WHILE @CAN>0
		BEGIN
		SELECT @IDLO=MAX(L.IDLOTE),@AUX=L.Cantidad-C.Cantidad
		FROM CONTROLP C INNER JOIN LOTE L ON C.IdLote = L.IdLote
		WHERE C.Cantidad < L.Cantidad AND L.IDPRODUCTO=@IDPRO
		GROUP BY L.IDLOTE,C.EXPIRACION,C.CANTIDAD,L.CANTIDAD
		HAVING C.Expiracion = (SELECT MAX(C.EXPIRACION)FROM CONTROLP C INNER JOIN LOTE L ON C.IdLote = L.IdLote
													 WHERE C.Cantidad < L.Cantidad AND L.IDPRODUCTO=@IDPRO)
		IF @AUX >= @CAN
			BEGIN
			UPDATE CONTROLP SET CANTIDAD=CANTIDAD+@CAN WHERE IDLOTE=@IDLO
			SET @CAN=0
			END
		ELSE
			BEGIN
			UPDATE CONTROLP SET CANTIDAD=CANTIDAD+@AUX WHERE IDLOTE=@IDLO
			SET @CAN=@CAN-@AUX
			END
		END


CREATE PROC GETCLIENTE @CI VARCHAR(20)
AS
	SELECT * FROM LISTARCLIENTES WHERE CICLIENTE=@CI
	
exec getcliente '1033'
SELECT * FROM LISTARPRODUCTOS

CREATE PROC GETPRODUCTO @COD VARCHAR(20)
AS
	SELECT * FROM LISTARPRODUCTOS WHERE CODIGO=@COD

EXEC GETPRODUCTO '123457'

ALTER PROC GETUSUARIO @CI VARCHAR(20)
AS
	SELECT * FROM LISTARUSUARIOS WHERE CIUSUARIO=@CI

ALTER PROC LOGINSYSTEM @CI VARCHAR(20),@CON VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM USUARIO WHERE CIUsuario=@CI AND CONTRASENA=@CON AND ESTADO='1')
		SELECT * FROM LISTARUSUARIOS WHERE CIUSUARIO=@CI AND CONTRASENA=@CON

SELECT * FROM LISTARDISTRIBUIDORAS

ALTER PROC INSERTARDISTRIBUIDORA @NOM VARCHAR(60),@DIR VARCHAR(60),@TEL VARCHAR(20),@CAT VARCHAR(40)
AS
	INSERT INTO DISTRIBUIDORA VALUES(@NOM,@DIR,@TEL,@CAT)

CREATE PROC EDITARDISTRIBUIDORA @ID INT,@NOM VARCHAR(60),@DIR VARCHAR(60),@TEL VARCHAR(20),@CAT VARCHAR(40)
AS
	UPDATE DISTRIBUIDORA SET NOMBRE=@NOM,DIRECCION=@DIR,TELEFONO=@TEL,CATEGORIA=@CAT WHERE IDDISTRIBUIDORA=@ID

	SELECT * FROM LISTARCOMPRAS
	select * from COMPRA

ALTER PROC LISTARVENTAUSUARIO @IDUSU INT,@FECINI DATE,@FECFIN DATE,@BAN CHAR(1)
AS
	IF @BAN='1'
		SELECT V.IDVENTA,U.NOMBRES+' '+U.APELLIDOS AS VENDEDOR,C.NOMBRES,V.FECHA,V.COSTOTOTAL,V.PAGO,V.ESTADO,V.EFECTIVO,V.CAMBIO
		FROM VENTA V INNER JOIN CLIENTE C ON V.IdCliente=C.IdCliente INNER JOIN USUARIO U ON U.IdUsuario=V.IdUsuario
		WHERE V.FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND V.ESTADO = '1'
	ELSE
		SELECT V.IDVENTA,U.NOMBRES+' '+U.APELLIDOS AS VENDEDOR,C.NOMBRES,V.FECHA,V.COSTOTOTAL,V.PAGO,V.ESTADO,V.EFECTIVO,V.CAMBIO
		FROM VENTA V INNER JOIN CLIENTE C ON V.IdCliente=C.IdCliente INNER JOIN USUARIO U ON U.IdUsuario=V.IdUsuario
		WHERE U.IDUSUARIO = @IDUSU AND V.FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND V.ESTADO = '1'

ALTER PROC CERRARCAJA @IDUSU INT,@FECINI DATE,@FECFIN DATE,@BAN CHAR(1)
AS
	IF @BAN='1'
		SELECT SUM(COSTOTOTAL) AS VENTATOTAL
		FROM VENTA
		WHERE FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND ESTADO = '1'
	ELSE
		SELECT SUM(COSTOTOTAL) AS VENTATOTAL
		FROM VENTA
		WHERE IDUSUARIO = @IDUSU AND FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND ESTADO = '1'

CREATE PROC LISTARLOTEVENTA @ID INT
AS
	SELECT * FROM LISTARLOTEVENTAS
	WHERE IDVENTA=@ID

	EXEC LISTARLOTECOMPRA 1022

ALTER PROC LISTARLOTECOMPRA @ID INT
AS
	SELECT * FROM LISTARLOTES WHERE IDCOMPRA=1020
	WHERE IDCOMPRA = @ID
	
	select * from COMPRA
	SELECT * FROM LOTE
EXEC LISTARVENTAUSUARIO 1,'2020/02/20','2020/02/20','0'
EXEC CERRARCAJA 1,'2020/02/20','2020/02/20','0'

select * from LISTARPRODUCTOS

CREATE PROC SEPARAR @ID INT,@NOM VARCHAR(60),@MAR VARCHAR(80)
AS
	UPDATE PRODUCTO SET NOMBRE = @NOM,MARCA=@MAR WHERE IDPRODUCTO=@ID

EXEC SEPARAR 27,'AGUA','VITAL'

CREATE PROC LISTARVENTASDIA @ID INT
AS
	SELECT * FROM LISTARVENTAS
	WHERE IDUSUARIO = @ID AND FECHA

CREATE PROC INSERTAREGRESO @IDU INT,@CAT VARCHAR(30),@MON FLOAT,@DES VARCHAR(120)
AS
	INSERT INTO EGRESO VALUES(@IDU,GETDATE(),@CAT,@MON,@DES)

CREATE PROC LISTARMISEGRESOS @IDU INT
AS
	SELECT * FROM LISTAREGRESOSHOY WHERE IDUSUARIO=@IDU


ALTER PROC ARQUEOVENTASHOY @IDU INT
AS
	SELECT * FROM LISTARARQUEOVENTASHOY WHERE IDUSUARIO=@IDU

EXEC ARQUEOVENTASHOY 1

CREATE PROC OBTENERMONTOVENTASHOY @IDU INT,@PAGO VARCHAR(20)
AS
	SELECT SUM(COSTOTOTAL) AS VENTASEFECTIVO
	FROM VENTA
	WHERE IDUSUARIO=@IDU AND ESTADO='1' AND PAGO=@PAGO
		  AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

CREATE PROC OBTENERINVERSIONESHOY @IDU INT
AS
	SELECT SUM(MONTO) AS INVERSIONES
	FROM INVERSION
	WHERE IDUSUARIO=@IDU
		  AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

SELECT * FROM VENTA
INSERT INTO INVERSION VALUES(5,1,560,GETDATE(),'PARA PAGAR A PIL')
SELECT * FROM INVERSION

EXEC OBTENERMONTOVENTASHOY 1,'TARJETA'
EXEC OBTENERINVERSIONESHOY 1

ALTER PROC ABRIRCAJA @IDU INT,@MON FLOAT
AS
	DECLARE @AUXMON FLOAT,@IDCA INT
	IF EXISTS(SELECT * FROM CAJA WHERE DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE()))
		BEGIN
		IF NOT EXISTS (SELECT * FROM CAJA WHERE IDUSUARIO=@IDU AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE()))
			BEGIN
			SET @IDCA = (SELECT IDCAJA FROM CAJA WHERE ULTIMO='1' AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE()))
			SET @AUXMON = (SELECT MONTO FROM CAJA WHERE IDCAJA=@IDCA)
			UPDATE CAJA SET ULTIMO='0' WHERE IDCAJA=@IDCA
			INSERT INTO CAJA VALUES(@IDU,@AUXMON,GETDATE(),'0','1','0')
			END
		END
	ELSE
		INSERT INTO CAJA VALUES(@IDU,@MON,GETDATE(),'0','1','1')

		select * from caja

ALTER PROC CERRARCAJA @IDU INT,@MON FLOAT
AS
	DECLARE @IDCA INT
	SET @IDCA = (SELECT IDCAJA FROM CAJA WHERE IDUSUARIO=@IDU AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE()))
	UPDATE CAJA SET MONTO=@MON,CIERRE='1' WHERE IDCAJA=@IDCA

EXEC CERRARCAJA 1,500
ALTER PROC OBTENERCAMBIOSHOY @IDU INT
AS
	SELECT MONTO FROM CAJA WHERE CIERRE='0' AND IDUSUARIO=@IDU
	AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

	update caja set idusuario=1,primero='1'
ALTER PROC CAJAABIERTA
AS
	SELECT U.IDUSUARIO,U.NOMBRES,U.APELLIDOS FROM CAJA C INNER JOIN USUARIO U ON C.IDUSUARIO=U.IDUSUARIO
	WHERE CIERRE='0'
	AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

	insert into usuario values('1037','Mari','Aran','4865','122','asdf','0','1','1234',800)
	
CREATE PROC PRIMERACAJA
AS
	IF EXISTS(SELECT * FROM CAJA WHERE DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE()))
		SELECT 'NO'
	ELSE
		SELECT 'SI'

CREATE PROC OBTENERMONTOCOMPRASHOY @IDU INT
AS
	SELECT SUM(COSTOTOTAL) FROM COMPRA
	WHERE IDUSUARIO=@IDU
	AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

CREATE PROC OBTENERGASTOSHOY @IDU INT
AS
	SELECT SUM(MONTO) FROM EGRESO WHERE IDUSUARIO=@IDU
	AND DAY(FECHA)=DAY(GETDATE()) AND MONTH(FECHA)=MONTH(GETDATE()) AND YEAR(FECHA)=YEAR(GETDATE())

update producto set precioventa=10 where idproducto=71

select * from producto where idproducto=71


select * from inversion

insert into usuario values('10380531','ADRIANA','LEON','65262743','','','0','1','',800)
insert into usuario values('10380531','ADRIANA','LEON','65262743','','','0','1','',800)

ALTER PROC INSERTARINVERSION @CIINV VARCHAR(20),@NOM VARCHAR(40),@IDUSU INT,@MON FLOAT,@DES VARCHAR(120)
AS
	INSERT INTO INVERSION VALUES(@CIINV,@NOM,@IDUSU,@MON,GETDATE(),@DES)

EXEC INSERTARINVERSION '','',,,''