ALTER PROC INSERTARPRODUCTO @IDPRO INT,@COD VARCHAR(20),@NOM VARCHAR(60), @MAR VARCHAR(80),@CON VARCHAR(20),@CAT VARCHAR(25),@PRECO FLOAT,@PREVE FLOAT,@DES VARCHAR(100),@UBI VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM PRODUCTO WHERE IDPRODUCTO = @IDPRO)
		BEGIN
		UPDATE PRODUCTO SET Codigo=@COD,Nombre=@NOM,Categoria=@CAT,PrecioCompra=@PRECO,PrecioVenta=@PREVE,Descripcion=@DES,MARCA=@MAR,CONTENIDO=@CON
		WHERE IdProducto=@IDPRO
		UPDATE ALMACEN SET UBICACION=@UBI WHERE IdProducto=@IDPRO
		END
	ELSE
		BEGIN
		INSERT INTO PRODUCTO VALUES(@COD,@NOM,@CAT,'',@PRECO,@PREVE,@DES,'1',@MAR,@CON)
		SET @IDPRO = (SELECT IDPRODUCTO FROM PRODUCTO WHERE CODIGO=@COD)
		INSERT INTO ALMACEN VALUES(@IDPRO,0,@UBI)
		END

						EXEC INSERTARPRODUCTO -1,'7771224002387','HELADO','DELIZIA BROWNIE','100 ML.','HELADOS\r',0,6,'','LADO IZQUIERDO'
						select * from lote l inner join controlp cp on l.idlote = cp.idlote
						UPDATE PRODUCTO SET MARCA='FERRARI G. MINI CRACKERS' WHERE IDPRODUCTO=1065

CREATE PROC ELIMINARPRODUCTO @IDPRO INT
AS
	UPDATE PRODUCTO SET ESTADO='0' WHERE IDPRODUCTO=@IDPRO

	
ALTER PROC INSERTARALMACEN @IDPRO INT,@CAN INT
AS
	UPDATE ALMACEN SET Cantidad = Cantidad + @CAN WHERE IdProducto = @IDPRO
	EXEC INSERTARLOTE 24,8,'19/02/2020',100,3,15

ALTER PROC INSERTARLOTE @IDPRO INT,@IDCO INT,@EXP VARCHAR(12),@COS FLOAT,@CANPA INT,@CANEN INT
AS
	DECLARE @PRECO FLOAT,@CAN INT
	SET @CAN = @CANPA * @CANEN
	SET @PRECO = @COS / @CAN
	INSERT INTO LOTE VALUES(@IDPRO,@IDCO,@EXP,@CAN,@PRECO,@COS,@CANPA,@CANEN)
	EXEC INSERTARALMACEN @IDPRO,@CAN
	UPDATE PRODUCTO SET PRECIOCOMPRA=@PRECO WHERE IDPRODUCTO=@IDPRO
	
CREATE PROC GETULTIMACOMPRA
AS
	SELECT IDCOMPRA FROM COMPRA WHERE ULTIMO='1'
	
CREATE PROC GETULTIMAVENTA
AS
	SELECT IDVENTA FROM VENTA WHERE ULTIMO='1'

	select * from DISTRIBUIDORA
			EXEC INSERTARCOMPRA 160,'MI PRIMER COMPRA','PIL','','',''


ALTER PROC INSERTARCOMPRA @COS FLOAT,@DES VARCHAR(200),@DIS VARCHAR(60),@DIR VARCHAR(60),@TEL VARCHAR(20),@CAT VARCHAR(25)
AS
	DECLARE @ID INT
	IF NOT EXISTS(SELECT * FROM DISTRIBUIDORA WHERE NOMBRE=@DIS)
		INSERT INTO DISTRIBUIDORA VALUES(@DIS,@DIR,@TEL,@CAT)
	SET @ID = (SELECT IDDISTRIBUIDORA FROM DISTRIBUIDORA WHERE NOMBRE=@DIS)
	INSERT INTO COMPRA VALUES(GETDATE(),@COS,1,@DES,@ID)

ALTER PROC EDITARCOMPRA @IDCOM INT,@COS FLOAT,@DES VARCHAR(100)
AS
	UPDATE COMPRA SET CostoTotal=@COS,ULTIMO='1',DESCRIPCION=@DES WHERE IdCompra=@IDCOM

CREATE PROC CERRARCOMPRA @IDCOM INT
AS
	UPDATE COMPRA SET ULTIMO = '0' WHERE IDCOMPRA = @IDCOM

CREATE PROC ELIMINARCONTROL @IDLO INT
AS
	DELETE FROM CONTROLP WHERE IDLOTE=@IDLO
	select * from compra
CREATE PROC ELIMINARCOMPRA @IDCOM INT
AS
	DELETE FROM COMPRA WHERE IdCompra=@IDCOM

ALTER PROC INSERTARUSUARIO @ID INT,@CI VARCHAR(20),@NOM VARCHAR(60),@APE VARCHAR(60),@TEL VARCHAR(20),@EM VARCHAR(40),@DIR VARCHAR(60),@ROL CHAR(1),@EST CHAR(1)
AS
	IF EXISTS(SELECT * FROM USUARIO WHERE IDUSUARIO=@ID)
		UPDATE USUARIO SET CIUsuario=@CI,Nombres=@NOM,Apellidos=@APE,Telefono=@TEL,Email=@EM,Direccion=@DIR,ROL=@ROL,ESTADO=@EST WHERE IDUSUARIO=@ID
	ELSE
		INSERT INTO USUARIO VALUES(@CI,@NOM,@APE,@TEL,@EM,@DIR,@ROL,'1')

CREATE PROC ELIMINARUSUARIO @ID INT
AS
	UPDATE USUARIO SET ESTADO='0' WHERE IDUSUARIO=@ID

CREATE PROC INSERTARCLIENTE @ID INT,@CI VARCHAR(20),@NOM VARCHAR(60),@APE VARCHAR(60),@TEL VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM CLIENTE WHERE IDCLIENTE=@ID)
		UPDATE CLIENTE SET CICliente=@CI,Nombres=@NOM,Apellidos=@APE,Telefono=@TEL WHERE IdCliente=@ID
	ELSE
		INSERT INTO CLIENTE VALUES(@CI,@NOM,@APE,@TEL)
		
ALTER PROC ELIMINARUSUARIO @ID INT
AS
	UPDATE USUARIO SET ESTADO='0' WHERE IDUSUARIO=@ID

ALTER PROC INSERTARVENTA @IDUSU INT,@CI VARCHAR(20),@NOM VARCHAR(60),@TEL VARCHAR(20),@COS FLOAT,@EFE FLOAT,@CAM FLOAT,@PA VARCHAR(10)
AS
	DECLARE @IDCLI INT
	IF NOT EXISTS(SELECT * FROM CLIENTE WHERE CICLIENTE=@CI)
		INSERT INTO CLIENTE VALUES(@CI,@NOM,'',@TEL)
	SET @IDCLI = (SELECT IDCLIENTE FROM CLIENTE WHERE CICLIENTE=@CI)
	INSERT INTO VENTA VALUES(@IDUSU,@IDCLI,GETDATE(),@COS,@EFE,@CAM,'1','1',@PA)

CREATE PROC EDITARVENTA @IDVEN INT,@COS FLOAT,@EFE FLOAT,@CAM FLOAT
AS
	UPDATE VENTA SET CostoTotal=@COS,Efectivo=@EFE,Cambio=@CAM WHERE IdVenta=@IDVEN

ALTER PROC BAJAVENTA @IDVEN INT
AS
	UPDATE VENTA SET ESTADO='0' WHERE IDVENTA=@IDVEN

CREATE PROC CERRARVENTA @IDVEN INT
AS
	UPDATE VENTA SET ULTIMO='0' WHERE IDVENTA=@IDVEN

ALTER PROC REDUCIRCONTROL @IDPRO INT,@CAN INT
AS
	DECLARE @IDLO INT,@AUX INT
	WHILE @CAN>0
		BEGIN
			SELECT @IDLO=MIN(IDLOTE),@AUX=CANTIDAD FROM CONTROLP
			WHERE Cantidad>0 AND IDPRODUCTO=@IDPRO
			GROUP BY IDLOTE,EXPIRACION,CANTIDAD
			HAVING Expiracion = (SELECT MIN(EXPIRACION)FROM CONTROLP WHERE CANTIDAD>0 AND IDPRODUCTO=@IDPRO)
			-----AQUI PUEDE ENTRAR EL FACTOR NULL
				IF @AUX>=@CAN
					BEGIN
					UPDATE CONTROLP SET CANTIDAD = CANTIDAD - @CAN WHERE IDLOTE=@IDLO
					SET @CAN = 0
					END
				ELSE
					BEGIN
					UPDATE CONTROLP SET CANTIDAD = 0 WHERE IDLOTE=@IDLO
					SET @CAN = @CAN - @AUX
					END

		END

				SELECT * FROM LISTARPRODUCTOS


				UPDATE PRODUCTO SET NOMBRE = 'CEPILLO DENTAL',MARCA='COLGATE NORMAL' WHERE IDPRODUCTO=1042
				UPDATE PRODUCTO SET NOMBRE = 'CEPILLO DENTAL',MARCA='ASTRAL NORMAL' WHERE IDPRODUCTO=1043
				
ALTER PROC INSERTARLOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT,@PREVE FLOAT,@COS FLOAT
AS
	DECLARE @NCAN INT
	SET @NCAN = @CAN * (-1)
	INSERT INTO LOTEVENTA VALUES(@IDVEN,@IDPRO,@CAN,@PREVE,'1',@COS)
	EXEC INSERTARALMACEN @IDPRO,@NCAN
	EXEC REDUCIRCONTROL @IDPRO,@CAN

	SELECT * FROM CONTROLP CP INNER JOIN ALMACEN A ON CP.IdProducto = A.IdProducto
	SELECT * FROM COMPRA C INNER JOIN LOTE L ON C.IDCOMPRA=L.IDCOMPRA

CREATE PROC DARBAJAVENTA @IDVEN INT
AS
	UPDATE VENTA SET ESTADO='0' WHERE IDVENTA=@IDVEN
	UPDATE LOTEVENTA SET ESTADO='0' WHERE IDVENTA=@IDVEN

ALTER PROC ELIMINARVENTA @IDVEN INT,@BAN INT
AS
	IF @BAN=1
		EXEC DARBAJAVENTA @IDVEN
	DELETE FROM VENTA WHERE IDVENTA=@IDVEN

ALTER PROC ELIMINARLOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT,@BAN INT
AS
	IF @BAN=1
		EXEC DARBAJALOTEVENTA @IDVEN,@IDPRO,@CAN
	DELETE FROM LOTEVENTA WHERE IDVENTA=@IDVEN AND IDPRODUCTO=@IDPRO

ALTER PROC DARBAJALOTEVENTA @IDVEN INT,@IDPRO INT,@CAN INT
AS
	DECLARE @IDLO INT,@AUX INT
	UPDATE ALMACEN SET CANTIDAD = CANTIDAD + @CAN WHERE IDPRODUCTO=@IDPRO
	WHILE @CAN>0
		BEGIN
		SELECT @IDLO=MAX(L.IDLOTE),@AUX=L.Cantidad-C.Cantidad
		FROM CONTROLP C INNER JOIN LOTE L ON C.IdLote = L.IdLote
		WHERE C.Cantidad < L.Cantidad AND L.IDPRODUCTO=@IDPRO
		GROUP BY L.IDLOTE,C.EXPIRACION,C.CANTIDAD,L.CANTIDAD
		HAVING C.Expiracion = (SELECT MAX(C.EXPIRACION)FROM CONTROLP C INNER JOIN LOTE L ON C.IdLote = L.IdLote
													 WHERE C.Cantidad < L.Cantidad AND L.IDPRODUCTO=@IDPRO)
		IF @AUX >= @CAN
			BEGIN
			UPDATE CONTROLP SET CANTIDAD=CANTIDAD+@CAN WHERE IDLOTE=@IDLO
			SET @CAN=0
			END
		ELSE
			BEGIN
			UPDATE CONTROLP SET CANTIDAD=CANTIDAD+@AUX WHERE IDLOTE=@IDLO
			SET @CAN=@CAN-@AUX
			END
		END


CREATE PROC GETCLIENTE @CI VARCHAR(20)
AS
	SELECT * FROM LISTARCLIENTES WHERE CICLIENTE=@CI
	
exec getcliente '1033'
SELECT * FROM LISTARPRODUCTOS

CREATE PROC GETPRODUCTO @COD VARCHAR(20)
AS
	SELECT * FROM LISTARPRODUCTOS WHERE CODIGO=@COD

EXEC GETPRODUCTO '123457'

ALTER PROC GETUSUARIO @CI VARCHAR(20)
AS
	SELECT * FROM LISTARUSUARIOS WHERE CIUSUARIO=@CI

ALTER PROC LOGINSYSTEM @CI VARCHAR(20),@CON VARCHAR(20)
AS
	IF EXISTS(SELECT * FROM USUARIO WHERE CIUsuario=@CI AND CONTRASENA=@CON AND ESTADO='1')
		SELECT * FROM LISTARUSUARIOS WHERE CIUSUARIO=@CI AND CONTRASENA=@CON

SELECT * FROM LISTARPRODUCTOS

CREATE PROC INSERTARDISTRIBUIDORA @NOM VARCHAR(60),@DIR VARCHAR(60),@TEL VARCHAR(20),@CAT VARCHAR(40)
AS
	IF EXISTS(SELECT * FROM DISTRIBUIDORA WHERE NOMBRE=@NOM)
		UPDATE DISTRIBUIDORA SET NOMBRE=@NOM,DIRECCION=@DIR,TELEFONO=@TEL,CATEGORIA=@CAT
	ELSE
		INSERT INTO DISTRIBUIDORA VALUES(@NOM,@DIR,@TEL,@CAT)

ALTER PROC LISTARVENTAUSUARIO @IDUSU INT,@FECINI DATE,@FECFIN DATE,@BAN CHAR(1)
AS
	IF @BAN='1'
		SELECT V.IDVENTA,CONCAT(U.NOMBRES,' ',U.APELLIDOS) AS VENDEDOR,C.NOMBRES,V.FECHA,V.COSTOTOTAL,V.PAGO,V.ESTADO,V.EFECTIVO,V.CAMBIO
		FROM VENTA V INNER JOIN CLIENTE C ON V.IdCliente=C.IdCliente INNER JOIN USUARIO U ON U.IdUsuario=V.IdUsuario
		WHERE V.FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND V.ESTADO = '1'
	ELSE
		SELECT V.IDVENTA,CONCAT(U.NOMBRES,' ',U.APELLIDOS) AS VENDEDOR,C.NOMBRES,V.FECHA,V.COSTOTOTAL,V.PAGO,V.ESTADO,V.EFECTIVO,V.CAMBIO
		FROM VENTA V INNER JOIN CLIENTE C ON V.IdCliente=C.IdCliente INNER JOIN USUARIO U ON U.IdUsuario=V.IdUsuario
		WHERE U.IDUSUARIO = @IDUSU AND V.FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND V.ESTADO = '1'

ALTER PROC CERRARCAJA @IDUSU INT,@FECINI DATE,@FECFIN DATE,@BAN CHAR(1)
AS
	IF @BAN='1'
		SELECT SUM(COSTOTOTAL) AS VENTATOTAL
		FROM VENTA
		WHERE FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND ESTADO = '1'
	ELSE
		SELECT SUM(COSTOTOTAL) AS VENTATOTAL
		FROM VENTA
		WHERE IDUSUARIO = @IDUSU AND FECHA BETWEEN @FECINI AND DATEADD(d,1,@FECFIN) AND ESTADO = '1'

CREATE PROC LISTARLOTEVENTA @ID INT
AS
	SELECT * FROM LISTARLOTEVENTAS
	WHERE IDVENTA=@ID

	EXEC LISTARLOTEVENTA 1025
EXEC LISTARVENTAUSUARIO 1,'2020/02/20','2020/02/20','0'
EXEC CERRARCAJA 1,'2020/02/20','2020/02/20','0'

select * from LISTARPRODUCTOS

CREATE PROC SEPARAR @ID INT,@NOM VARCHAR(60),@MAR VARCHAR(80)
AS
	UPDATE PRODUCTO SET NOMBRE = @NOM,MARCA=@MAR WHERE IDPRODUCTO=@ID

	UPDATE PRODUCTO SET NOMBRE='AGUA VITAL' WHERE IDPRODUCTO=27
EXEC SEPARAR 27,'AGUA','VITAL'