CREATE TRIGGER ALINSERTARPRODUCTO ON PRODUCTO FOR INSERT
AS
	DECLARE @ID INT
	SET @ID = (SELECT IDPRODUCTO FROM INSERTED)
	EXEC INSERTARALMACEN @ID,0

CREATE TRIGGER ALELIMINARALMACEN ON ALMACEN FOR DELETE
AS
	DECLARE @ID INT
	SET @ID = (SELECT IDPRODUCTO FROM DELETED)
	DELETE FROM PRODUCTO WHERE IDPRODUCTO = @ID

CREATE TRIGGER ALELIMINARLOTE ON LOTE FOR DELETE
AS
	DECLARE @IDPRO INT,@CAN INT
	SELECT @IDPRO=IDPRODUCTO,@CAN=Cantidad FROM DELETED
	UPDATE ALMACEN SET Cantidad = Cantidad - @CAN WHERE IDPRODUCTO = @IDPRO

CREATE TRIGGER ALELIMINARCONTROLP ON CONTROLP FOR DELETE
AS
	DECLARE @IDLO INT
	SET @IDLO = (SELECT IDLOTE FROM DELETED)
	DELETE FROM LOTE WHERE IDLOTE = @IDLO

create TRIGGER ALINSERTARLOTE ON LOTE FOR INSERT
AS
	DECLARE @IDLO INT,@IDPRO INT,@EXP DATE,@CAN INT,@PRECO FLOAT
	SELECT @IDLO=IDLOTE,@IDPRO=IDPRODUCTO,@EXP=EXPIRACION,@CAN=CANTIDAD,@PRECO=PRECIOCOMPRA FROM INSERTED
	INSERT INTO CONTROLP VALUES(@IDLO,@IDPRO,@EXP,@CAN)
	UPDATE PRODUCTO SET PRECIOCOMPRA = @PRECO WHERE IDPRODUCTO = @IDPRO

	select * from controlp