ALTER VIEW LISTARPRODUCTOS
AS
	SELECT ROW_NUMBER() OVER(ORDER BY P.NOMBRE ASC) AS N,P.IDPRODUCTO,P.CODIGO,P.NOMBRE,P.MARCA,P.CONTENIDO,P.CATEGORIA,P.PRECIOCOMPRA,P.PRECIOVENTA,P.DESCRIPCION,A.UBICACION,A.CANTIDAD
	FROM PRODUCTO P INNER JOIN ALMACEN A ON P.IdProducto = A.IdProducto
	WHERE P.ESTADO='1'
	
select * from LISTARUSUARIOS
select * from usuario
CREATE VIEW LISTARCONTROL
AS
	SELECT CP.IDLOTE,P.CODIGO,P.Nombre + ' ' + P.MARCA AS PRODUCTO,CP.CANTIDAD,CP.EXPIRACION
	FROM CONTROLP CP INNER JOIN PRODUCTO P ON CP.IDPRODUCTO=P.IDPRODUCTO

SELECT * FROM LISTARCONTROL ORDER BY EXPIRACION
	
SELECT * FROM LISTARPRODUCTOS

select * from listarCompras

ALTER VIEW LISTARCOMPRAS
AS
	SELECT IDCOMPRA,U.Nombres + ' ' + U.Apellidos AS VENDEDOR,D.Nombre AS DISTRIBUIDORA,(cast(DAY(C.FECHA) as varchar) + cast('/' as varchar) + cast(MONTH(C.FECHA) as varchar) + cast('/' as varchar) + cast(YEAR(C.FECHA) as varchar) + ' ' + cast(CONVERT(CHAR(8),C.FECHA, 108) as varchar)) AS FECHA,C.COSTOTOTAL,C.DESCRIPCION
	FROM COMPRA C INNER JOIN USUARIO U ON C.IDUSUARIO=U.IDUSUARIO INNER JOIN DISTRIBUIDORA D ON D.IdDistribuidora = C.IdDistribuidora
	
CREATE VIEW LISTARDISTRIBUIDORAS
AS
	SELECT NOMBRE FROM DISTRIBUIDORA

	SELECT * FROM LISTARDISTRIBUIDORAS ORDER BY NOMBRE
	
	
ALTER VIEW LISTARLOTES
AS
	SELECT L.IDCOMPRA,L.IDLOTE,P.CODIGO,P.NOMBRE + ' ' + P.Marca AS PRODUCTO,P.CONTENIDO,L.PRECIOCOMPRA,L.CANTIDAD,l.Costo,L.CantidadPaquete,L.CantidadEnPaquete,L.EXPIRACION
	FROM LOTE L INNER JOIN PRODUCTO P ON P.IDPRODUCTO=L.IDPRODUCTO INNER JOIN COMPRA C ON C.IdCompra = L.IdCompra

SELECT * FROM LISTARPRODUCTOS

ALTER VIEW LISTARCONTROLES
AS
	SELECT CP.IDLOTE,P.NOMBRE,P.PRESENTACION,CP.EXPIRACION,CP.CANTIDAD
	FROM CONTROLP CP INNER JOIN PRODUCTO P ON CP.IDPRODUCTO=P.IDPRODUCTO

ALTER VIEW LISTARUSUARIOS
AS
	SELECT ROW_NUMBER() OVER(ORDER BY NOMBRES ASC) AS N,*
	FROM USUARIO


ALTER VIEW LISTARCLIENTES
AS
	SELECT ROW_NUMBER() OVER(ORDER BY NOMBRES ASC) AS N,*
	FROM CLIENTE
	WHERE IDCLIENTE>1

SELECT * FROM producto

select * from LISTARVENTAShoy
ALTER VIEW LISTARVENTAS
AS
	SELECT V.IDVENTA,U.IDUSUARIO,C.IDCLIENTE,U.NOMBRES + ' ' + U.APELLIDOS AS VENDEDOR,C.NOMBRES AS CLIENTE,C.CICLIENTE,CAST(DAY(V.FECHA) AS VARCHAR) + '/' + CAST(MONTH(V.FECHA) AS VARCHAR) + '/' + CAST(YEAR(V.FECHA) AS VARCHAR) + ' ' + CAST(convert(char(8), V.FECHA, 108) AS VARCHAR) AS FECHA,V.COSTOTOTAL,V.PAGO,V.EFECTIVO,V.CAMBIO,V.ESTADO,V.DESCRIPCION
	FROM VENTA V INNER JOIN USUARIO U ON V.IDUSUARIO=U.IDUSUARIO
				 INNER JOIN CLIENTE C ON V.IDCLIENTE=C.IDCLIENTE
		
CREATE VIEW LISTARVENTASHOY
AS
	SELECT V.IDVENTA,U.IDUSUARIO,C.IDCLIENTE,U.NOMBRES + ' ' + U.APELLIDOS AS VENDEDOR,C.NOMBRES AS CLIENTE,C.CICLIENTE,CAST(DAY(V.FECHA) AS VARCHAR) + '/' + CAST(MONTH(V.FECHA) AS VARCHAR) + '/' + CAST(YEAR(V.FECHA) AS VARCHAR) + ' ' + CAST(convert(char(8), V.FECHA, 108) AS VARCHAR) AS FECHA,V.COSTOTOTAL,V.PAGO,V.EFECTIVO,V.CAMBIO,V.ESTADO,V.DESCRIPCION
	FROM VENTA V INNER JOIN USUARIO U ON V.IDUSUARIO=U.IDUSUARIO
				 INNER JOIN CLIENTE C ON V.IDCLIENTE=C.IDCLIENTE
	WHERE DAY(V.Fecha) = DAY(GETDATE()) AND MONTH(V.FECHA) = MONTH(GETDATE()) AND YEAR(V.FECHA) = YEAR(GETDATE())
	
ALTER VIEW LISTARCOMPRASHOY
AS
	SELECT C.IdCompra,U.NOMBRES + ' ' + U.APELLIDOS AS USUARIO,D.NOMBRE AS DISTRIBUIDORA,C.FECHA,C.COSTOTOTAL,C.DESCRIPCION,U.IdUsuario
	FROM COMPRA C INNER JOIN USUARIO U ON U.IDUSUARIO=C.IDUSUARIO
				  INNER JOIN DISTRIBUIDORA D ON D.IdDistribuidora=C.IdDistribuidora
	WHERE DAY(C.Fecha) = DAY(GETDATE()) AND MONTH(C.FECHA) = MONTH(GETDATE()) AND YEAR(C.FECHA) = YEAR(GETDATE())
		
		SELECT * FROM LISTARCOMPRASHOY

		select * from LISTARLOTES

ALTER VIEW LISTARLOTEVENTAS
AS
	SELECT LV.IDVENTA,P.CODIGO,P.NOMBRE,P.MARCA,P.CONTENIDO,LV.PRECIOVENTA,LV.CANTIDAD,LV.CANTIDAD*LV.PRECIOVENTA AS COSTO,LV.ESTADO
	FROM LOTEVENTA LV INNER JOIN PRODUCTO P ON LV.IDPRODUCTO=P.IDPRODUCTO

	select * from listarloteventas

ALTER VIEW LISTARSALARIOS
AS
	SELECT S.IDSALARIO,U.CIUSUARIO,U.NOMBRES + ' ' + U.APELLIDOS AS VENDEDOR,S.MESPAGADO,U.SUELDO,S.DESCUENTO,S.LIQUIDOPAGABLE,S.FECHA,S.DESCRIPCION
	FROM SALARIO S INNER JOIN USUARIO U ON S.IDUSUARIO=U.IDUSUARIO

ALTER VIEW LISTAREGRESOS
AS
	SELECT E.IDEGRESO,U.IDUSUARIO,U.NOMBRES + ' ' + U.APELLIDOS AS USUARIO,E.FECHA,E.CATEGORIA,E.MONTO,E.DESCRIPCION
	FROM EGRESO E INNER JOIN USUARIO U ON E.IDUSUARIO = U.IDUSUARIO

CREATE VIEW LISTAREGRESOSHOY
AS
	SELECT * FROM LISTAREGRESOS
	WHERE DAY(Fecha) = DAY(GETDATE()) AND MONTH(FECHA) = MONTH(GETDATE()) AND YEAR(FECHA) = YEAR(GETDATE())

CREATE VIEW LISTARARQUEOVENTASHOY
AS
	SELECT V.IDVENTA,P.CODIGO,P.NOMBRE + ' ' + P.MARCA AS PRODUCTO,P.CONTENIDO,LV.CANTIDAD,LV.PRECIOVENTA,LV.COSTO,V.IDUSUARIO
	FROM VENTA V INNER JOIN LOTEVENTA LV ON V.IdVenta = LV.IdVenta INNER JOIN PRODUCTO P ON P.IDPRODUCTO=LV.IDPRODUCTO
	WHERE DAY(V.Fecha) = DAY(GETDATE()) AND MONTH(V.FECHA) = MONTH(GETDATE()) AND YEAR(V.FECHA) = YEAR(GETDATE()) AND V.ESTADO='1'


SELECT * FROM ARQUEOVENTAS