ALTER VIEW LISTARPRODUCTOS
AS
	SELECT ROW_NUMBER() OVER(ORDER BY P.NOMBRE ASC) AS N,P.IDPRODUCTO,P.CODIGO,P.NOMBRE,P.MARCA,P.CONTENIDO,P.CATEGORIA,P.PRECIOCOMPRA,P.PRECIOVENTA,P.DESCRIPCION,A.UBICACION,A.CANTIDAD
	FROM PRODUCTO P INNER JOIN ALMACEN A ON P.IdProducto = A.IdProducto
	WHERE P.ESTADO='1'
	
SELECT * FROM LISTARPRODUCTOS

ALTER VIEW LISTARCOMPRAS
AS
	SELECT IDCOMPRA,(cast(DAY(FECHA) as varchar) + cast('/' as varchar) + cast(MONTH(FECHA) as varchar) + cast('/' as varchar) + cast(YEAR(FECHA) as varchar) + ' ' + cast(CONVERT(CHAR(8),FECHA, 108) as varchar)) AS FECHA,COSTOTOTAL,DESCRIPCION
	FROM COMPRA

	select * from listarcompras

CREATE VIEW LISTARLOTES
AS
	SELECT L.IDCOMPRA,L.IDLOTE,P.NOMBRE,P.PRESENTACION,L.PRECIOCOMPRA,L.CANTIDAD,L.CANTIDAD*L.PRECIOCOMPRA AS COSTO
	FROM LOTE L INNER JOIN PRODUCTO P ON P.IDPRODUCTO=L.IDPRODUCTO

ALTER VIEW LISTARCONTROLES
AS
	SELECT CP.IDLOTE,P.NOMBRE,P.PRESENTACION,CP.EXPIRACION,CP.CANTIDAD
	FROM CONTROLP CP INNER JOIN PRODUCTO P ON CP.IDPRODUCTO=P.IDPRODUCTO

ALTER VIEW LISTARUSUARIOS
AS
	SELECT ROW_NUMBER() OVER(ORDER BY NOMBRES ASC) AS N,*
	FROM USUARIO
	

ALTER VIEW LISTARCLIENTES
AS
	SELECT ROW_NUMBER() OVER(ORDER BY NOMBRES ASC) AS N,*
	FROM CLIENTE
	WHERE IDCLIENTE>1

SELECT * FROM producto


ALTER VIEW LISTARVENTAS
AS
	SELECT V.IDVENTA,U.IDUSUARIO,C.IDCLIENTE,U.NOMBRES + ' ' + U.APELLIDOS AS VENDEDOR,C.NOMBRES AS CLIENTE,C.CICLIENTE,CAST(DAY(V.FECHA) AS VARCHAR) + '/' + CAST(MONTH(V.FECHA) AS VARCHAR) + '/' + CAST(YEAR(V.FECHA) AS VARCHAR) + ' ' + CAST(convert(char(8), V.FECHA, 108) AS VARCHAR) AS FECHA,V.COSTOTOTAL,V.PAGO,V.EFECTIVO,V.CAMBIO,V.ESTADO
	FROM VENTA V INNER JOIN USUARIO U ON V.IDUSUARIO=U.IDUSUARIO
				 INNER JOIN CLIENTE C ON V.IDCLIENTE=C.IDCLIENTE
		
		SELECT * FROM LISTARVENTAS

ALTER VIEW LISTARLOTEVENTAS
AS
	SELECT LV.IDVENTA,P.CODIGO,P.NOMBRE,P.MARCA,P.CONTENIDO,LV.PRECIOVENTA,LV.CANTIDAD,LV.CANTIDAD*LV.PRECIOVENTA AS COSTO,LV.ESTADO
	FROM LOTEVENTA LV INNER JOIN PRODUCTO P ON LV.IDPRODUCTO=P.IDPRODUCTO

	select * from listarloteventas

SELECT * FROM LISTARPRODUCTOS WHERE NOMBRE LIKE 'CIGARR%'

UPDATE PRODUCTO SET CATEGORIA='LIBRERIA' WHERE IDPRODUCTO=1114
select * from listarproductos where nombre like 'PI%'